'use client'

import { useState } from 'react'

const daysOfWeek = ['Ma', 'Ti', 'Ke', 'To', 'Pe', 'La', 'Su']

// Mock weekly plan — will be generated by Study Plan agent
const mockPlan = {
  week_number: 12,
  days: [
    {
      day: 'Ma',
      topics: [
        { id: '1.1', name: 'Kysyntä ja tarjonta', format: 'Teksti + video', pomodoros: 2 },
        { id: '3.1', name: 'Kuvaileva tilastotiede', format: 'Harjoitustehtävät', pomodoros: 2 },
      ],
      total_hours: 2,
      sr_cards: 8,
    },
    {
      day: 'Ti',
      topics: [
        { id: '2.1', name: 'BKT', format: 'Teksti + Feynman', pomodoros: 3 },
      ],
      total_hours: 1.5,
      sr_cards: 12,
    },
    {
      day: 'Ke',
      topics: [
        { id: '1.3', name: 'Joustavuus', format: 'Video + tehtävät', pomodoros: 2 },
        { id: '3.3', name: 'Todennäköisyyslaskenta', format: 'Laskuharjoitukset', pomodoros: 2 },
      ],
      total_hours: 2,
      sr_cards: 10,
    },
    {
      day: 'To',
      topics: [
        { id: '2.4', name: 'Inflaatio', format: 'Teksti + video', pomodoros: 2 },
        { id: '4.2', name: 'Tilinpäätös', format: 'Harjoitustehtävät', pomodoros: 1 },
      ],
      total_hours: 1.5,
      sr_cards: 15,
    },
    { day: 'Pe', topics: [], total_hours: 0, sr_cards: 5 },
    {
      day: 'La',
      topics: [
        { id: 'exam', name: 'Harjoituskoe', format: 'Koko koe (3h)', pomodoros: 0 },
      ],
      total_hours: 3,
      sr_cards: 0,
    },
    { day: 'Su', topics: [], total_hours: 0, sr_cards: 0 },
  ],
}

export default function StudyPlanPage() {
  const [currentDay, setCurrentDay] = useState(
    new Date().getDay() === 0 ? 6 : new Date().getDay() - 1
  )

  const plan = mockPlan
  const totalWeekHours = plan.days.reduce((a, d) => a + d.total_hours, 0)

  return (
    <div className="max-w-4xl mx-auto px-6 py-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Opiskelusuunnitelma</h1>
          <p className="text-gray-600 mt-1">Viikko {plan.week_number} — {totalWeekHours}h suunniteltu</p>
        </div>
        <button className="bg-brand-600 text-white px-5 py-2.5 rounded-lg text-sm font-medium hover:bg-brand-700">
          Luo uusi suunnitelma
        </button>
      </div>

      {/* Week overview */}
      <div className="grid grid-cols-7 gap-2 mb-8">
        {plan.days.map((day, i) => (
          <button
            key={day.day}
            onClick={() => setCurrentDay(i)}
            className={`rounded-xl p-3 text-center transition-colors ${
              i === currentDay
                ? 'bg-brand-600 text-white'
                : day.total_hours > 0
                ? 'bg-white border hover:border-brand-300'
                : 'bg-gray-50 border border-gray-100'
            }`}
          >
            <div className="text-xs font-medium mb-1">{day.day}</div>
            <div className={`text-lg font-bold ${i === currentDay ? '' : 'text-gray-900'}`}>
              {day.total_hours > 0 ? `${day.total_hours}h` : '—'}
            </div>
            <div
              className={`text-xs mt-1 ${i === currentDay ? 'text-blue-100' : 'text-gray-400'}`}
            >
              {day.topics.length > 0 ? `${day.topics.length} aihetta` : 'Vapaapäivä'}
            </div>
          </button>
        ))}
      </div>

      {/* Day detail */}
      <div className="bg-white border rounded-xl p-6">
        <h2 className="font-semibold text-lg mb-4">
          {daysOfWeek[currentDay]}
          {plan.days[currentDay].total_hours === 0
            ? ' — Vapaapäivä'
            : ` — ${plan.days[currentDay].total_hours}h`}
        </h2>

        {plan.days[currentDay].sr_cards > 0 && (
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-4">
            <div className="flex items-center gap-2">
              <span>🔄</span>
              <span className="text-sm font-medium text-purple-800">
                Kertaus: {plan.days[currentDay].sr_cards} muistikorttia
              </span>
            </div>
          </div>
        )}

        {plan.days[currentDay].topics.length > 0 ? (
          <div className="space-y-3">
            {plan.days[currentDay].topics.map((topic, i) => (
              <div
                key={i}
                className="border rounded-lg p-4 flex items-center justify-between"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono text-gray-400">{topic.id}</span>
                  </div>
                  <h3 className="font-medium text-gray-900">{topic.name}</h3>
                  <p className="text-sm text-gray-500">{topic.format}</p>
                </div>
                {topic.pomodoros > 0 && (
                  <div className="text-right">
                    <div className="flex gap-1">
                      {Array.from({ length: topic.pomodoros }).map((_, j) => (
                        <span key={j} className="text-lg">🍅</span>
                      ))}
                    </div>
                    <span className="text-xs text-gray-500">
                      {topic.pomodoros * 25} min
                    </span>
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          <p className="text-gray-500 text-center py-8">
            Tänään on vapaapäivä. Lepo on tärkeää oppimiselle!
          </p>
        )}
      </div>
    </div>
  )
}
